### ISSUE TITLE
Pembuatan desain stampel 

### ISSUE THREAD

**Issue by Widya-available** [Kartikasari-2024/KSM-Task#10]
1. IT -DESIGN SOBA
2. Design stempel 
3. Widya
4. Pembuatan desain stampel (ukuran p= 8 l = 5)
[KEK GINI YES.docx](https://github.com/user-attachments/files/17878155/KEK.GINI.YES.docx)

**Comment by Ikhwanulsatya** [comment]
Ukuran stempel mbak?

**Comment by Widya-available** [comment]
(ukuran p= 8 l = 5)

**Comment by Ikhwanulsatya** [comment]
On Going

**Comment by Ikhwanulsatya** [comment]
![Preview](https://github.com/user-attachments/assets/625fcb44-9462-424f-b766-8ae9053bde8a)

**Comment by Widya-available** [comment]
ini caranya download filenya gimana ges?

**Comment by Ikhwanulsatya** [comment]
Itu preview

**Comment by Ikhwanulsatya** [comment]
Kalok udah oke baru tak kirim file jadinya

**Comment by Widya-available** [comment]
oalah, 
oke sudah mas gituu, 
makasih ya 
mintol di kirim filenya... 
pakek yang wrna hitam saja,

**Comment by Ikhwanulsatya** [comment]
> ![Stamp 2](https://private-user-images.githubusercontent.com/189087352/389162098-fe116ce2-c91d-4ada-b9cb-031816e6fd74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMzQwNzIsIm5iZiI6MTczMjMzMzc3MiwicGF0aCI6Ii8xODkwODczNTIvMzg5MTYyMDk4LWZlMTE2Y2UyLWM5MWQtNGFkYS1iOWNiLTAzMTgxNmU2ZmQ3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QwMzQ5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmFlZmU2YjU1Zjc5MGY4NmY3MWU0OTIyZmUwMTE0MzlhZmMyNWRmMDI5YTgwMjRlYzhmNDAyOWI0NDE5NTAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jm0V6WnjzxsZ3s2E3jI_01iyY8mkQmpE_NQgM4mTVzE)
> 
> PNG Hires

Ini sudah terlampir mbak yg hires siap cetak

**Comment by Widya-available** [comment]
mas ini ukurannya benar 40kb a?

**Comment by Ikhwanulsatya** [comment]
[Stamp.zip](https://github.com/user-attachments/files/17878742/Stamp.zip)

**Comment by Ikhwanulsatya** [comment]
Salah download mbak, cobak download yg tak lampirkan terakhir
