### ISSUE TITLE
PEMBUATAN STAMPEL QC UNTUK FO

### ISSUE THREAD

**Issue by Widya-available** [Kartikasari-2024/KSM-Task#11]
1. IT -DESIGN SOBA
2. Design stempel
3. Widya
4. Pembuatan desain stampel (bulat d 3cm)
[STAMPEL QC BULAT.docx](https://github.com/user-attachments/files/17896751/STAMPEL.QC.BULAT.docx)

**Comment by Widya-available** [comment]
mas lupa 
bikinnya 3 yes, 
QC 1, QC 2, QC 3 
design nya sama semua yes, 
makasih kakak

**Comment by Sobaaa7** [comment]
Okey

**Comment by Sobaaa7** [comment]
![STEMPEL 1](https://github.com/user-attachments/assets/9f6a43d2-787c-40d5-a855-5e0268b24fd5)
![STEMPEL 2](https://github.com/user-attachments/assets/182546e2-5ba7-4b8a-b931-591011f331c4)
![STEMPEL 3](https://github.com/user-attachments/assets/2c6a1fdc-b4d4-494d-bf1a-686e868aef22)

**Comment by Widya-available** [comment]
oke kak 
pakek gambar yang no 3 yes, 
lanjut bikin QC 2,QC 3 kak, 
jadi total ada 3 yes, 
makasih banyak

**Comment by Sobaaa7** [comment]
![STEMPEL 1](https://github.com/user-attachments/assets/da9d4278-9602-4fe8-b50a-e45fce8c60bb)
![STEMPEL 2](https://github.com/user-attachments/assets/3cdeb711-0ab9-42c9-8d92-0e6b631625c0)
![STEMPEL 3](https://github.com/user-attachments/assets/5d9cad99-2e65-4042-b311-5278fa4caae5)

**Comment by Widya-available** [comment]
terbaeeekkk
wes begitu kak
filenya yes, 
tingkyuuu

**Comment by Sobaaa7** [comment]
bisa langsung klik kanan save kak, udah tak coba ukurannya sama kok dengan file aslinya

**Comment by Widya-available** [comment]
oke terimakasih banyaaakk kakak
