### ISSUE TITLE
PRINTER KELAP KELIP TOLONG

### ISSUE THREAD

**Issue by Widya-available** [Kartikasari-2024/KSM-Task#12]
1. IT JAMIL
2. LAMPU PRINTER KELAP KELIP 
3. WIDYA
4. TOLONG GES GAK BISA-BISA SUDAH DI CABUT KABEL TETEP SAJA KELAP KELIP KEK LAMPU DISKO

**Comment by Kartikasari-2024** [comment]
DONE
