### ISSUE TITLE
PROMO REM (BENGKEL MONDOROKO)

### ISSUE THREAD

**Issue by dinaalfian10** [Kartikasari-2024/KSM-Task#14]
Tolong di bantu untuk membuat materi promo bengkel Gr mondoroko
[voucher rem.xlsx](https://github.com/user-attachments/files/17914497/voucher.rem.xlsx)

Terima kasih

**Comment by Ikhwanulsatya** [comment]
On Going

**Comment by Ikhwanulsatya** [comment]
![Voucher Service Rem](https://github.com/user-attachments/assets/29bc8181-1edd-40d0-badf-35c6e46bb3b3)
