### ISSUE TITLE
GANTI TINTA PRINTER

### ISSUE THREAD

**Issue by Laurent-666** [Kartikasari-2024/KSM-Task#15]
1. IT-JAMIL
2. TINTA PRINTER
3. ITA (ADMIN-FAKTUR)
4. GANTI TINTA PRINTER HITAM 2, KUNING 1, BIRU 1, MERAH 1 DI PRINTER ADMIN STNK.
![WhatsApp Image 2024-11-28 at 9 36 47 AM](https://github.com/user-attachments/assets/17e433cb-5ac2-44bf-a08d-8d5ab1d537a2)

**Comment by Kartikasari-2024** [comment]
DONE
