### ISSUE TITLE
Program Promo Bengkel week 1-2 desember (diskon & service pengecekan)

### ISSUE THREAD

**Issue by syams-ramadhan** [Kartikasari-2024/KSM-Task#22]
Desain program promo bengkel, jadi 1 gambar :
1. diskon 45% jasa service berkala ganti oli s/d tgl 18 Desember 2024
2. pengecekan kondisi kendaraan (General Check) persiapan libur tahun baru

**Comment by Sobaaa7** [comment]
ukuran wa blash ya pak?

**Comment by Sobaaa7** [comment]
![image](https://github.com/user-attachments/assets/3a5ecd22-f6d2-4cd6-b362-4fe65c4a7758)
