### ISSUE TITLE
TAMBAHAN MENU REMINDER KSM-SALES

### ISSUE THREAD

**Issue by nanikandriani20** [Kartikasari-2024/KSM-Task#30]
Example untuk ksm-sales:

IT JAMIL
CREATE DI MENU REMINDER KSM SALES : STNK JADI, NOTICE PLAT JADI DAN BPKB JADI  dan YANG BELUM DIAMBIL
Nanik ADMIN
Buatkan tambahan menu reminder di aplikasi KSM SALES data untuk tanggal STNK JADI, NOTICE PLAT JADI dan BPKB JADI dan yang belum diambil
[KOLOM EXCEL.xlsx](https://github.com/user-attachments/files/18004047/KOLOM.EXCEL.xlsx)

**Comment by Kartikasari-2024** [comment]
DONE
