### ISSUE TITLE
MATERI PROMO REM KS-MONDOROKO

### ISSUE THREAD

**Issue by dinaalfian10** [Kartikasari-2024/KSM-Task#34]
Mas Annul mintak tlong di buatkan materi promo paket rem,
desain sama seperti yg sebelum nya
NB : 1. nominal biaya 550k di coret menjadi 350k
berlaku s/d tgl 14 des 2024
2. gambar mobil di ganti mobil innova reborn & zenix
3. warna voucher tlng di ganti mas

Terima kasih.

**Comment by Ikhwanulsatya** [comment]
![Uploading Voucher Service Rem 2.jpg…]()

**Comment by Ikhwanulsatya** [comment]
![Voucher Service Rem 2](https://github.com/user-attachments/assets/7da36930-73fd-4406-a3fd-c0f93150c53a)

**Comment by Ikhwanulsatya** [comment]
![Voucher Service Rem 2](https://github.com/user-attachments/assets/e8bd6330-9aca-4c8b-826c-dae12acd2eda)
