### ISSUE TITLE
WORDNYA HILANG MINTA TOLONG CARIIN

### ISSUE THREAD

**Issue by Widya-available** [Kartikasari-2024/KSM-Task#35]
FORMAT ISSUE:
1. IT-ADIT
2. WORD DI KOMPUTER HILANG
3. WIDYA
4. WORD DI KOMPUTER HILANG ENTAH KEMANA KEKNYA CAPEK KERJA

**Comment by AWF3** [comment]
CAPEEK 😣

**Comment by AWF3** [comment]
OKE LANJUT

**Comment by Kartikasari-2024** [comment]
DONE

**Comment by Widya-available** [comment]
kak altiusnya ganti yang nggak ada i kemana ini?
