### ISSUE TITLE
Check Log App KSM

### ISSUE THREAD

**Issue by LBlaze99** [Kartikasari-2024/KSM-Task#46]
1.     IT Jamil
2.     Menu Check Log
3.     HRD
4.     Tambahkan history check log di menu check log

penambahan history check log dengan periode tertentu di menu check log agar masing2 karyawan ksm bisa mengecek dan mengontrol absensinya masing2

**Comment by Kartikasari-2024** [comment]
DONE

**Comment by Kartikasari-2024** [comment]
Penambahan ICON

**Comment by Kartikasari-2024** [comment]
DONE
