### ISSUE TITLE
Tidak Bisa Akses File Explorer/Network 

### ISSUE THREAD

**Issue by salmahcantik** [Kartikasari-2024/KSM-Task#59]
1. IT Jamil 
2. Tidak bisa akses file explorer/network Global dll 
3. Salmah CRC
4. Tolong bantu cek an komputer saya kenapa begini 
5. -

![image](https://github.com/user-attachments/assets/769687f8-e099-426f-b56b-5234020aa379)
![image](https://github.com/user-attachments/assets/0355dfd4-7c76-413e-bd70-a7928a7b3786)

**Comment by Kartikasari-2024** [comment]
DONE
