### ISSUE TITLE
Penambahan form persetuan penggunaan data diri customer di web kartika sari mulia

### ISSUE THREAD

**Issue by Widya-available** [Kartikasari-2024/KSM-Task#6]
1. IT JAMIL 
2. Form persetujuan
3. Widya
4. Minta tolong untuk di tambahkan form persetujuan penggunaan data diri customer di web milik kartika sari. adapun contoh nya dapat di lihat pada https://www.toyota.astra.co.id/privacy-policy

**Comment by Kartikasari-2024** [comment]
FTP Tidak Stabil

**Comment by Kartikasari-2024** [comment]
Done, silahkan di cek dulu mbak widya, kalau nanti masih ada kekurang bisa di re-open issue nya
