### ISSUE TITLE
MATERI PROMO EVEN LUMAJANG

### ISSUE THREAD

**Issue by dinaalfian10** [Kartikasari-2024/KSM-Task#60]
mas tlong di bantu buat materi promo event lumajang di tgl 26/12/2024

judul : PROMO SERU NATARU
HANYA DI KARTIKA SARI LUMAJANG
[MATERI EVENT LUMAJANG.docx](https://github.com/user-attachments/files/18235415/MATERI.EVENT.LUMAJANG.docx)

**Comment by Ikhwanulsatya** [comment]
![image](https://github.com/user-attachments/assets/c553a0fd-4ae9-4bd3-883a-a9a60c63d8f8)

Bisa dibantu Alamat sma Contact personnya ya mbak
