### ISSUE TITLE
Design stempel MRA

### ISSUE THREAD

**Issue by amaliarosariniii** [Kartikasari-2024/KSM-Task#8]

**Comment by Ikhwanulsatya** [comment]
Deskripsi tolong mbak

**Comment by amaliarosariniii** [comment]
Bantuan TIM IT untuk membuatkan design stempel customer Non-Fir

**Comment by Ikhwanulsatya** [comment]
Apakah ada text dalam stempelnya?

**Comment by Ikhwanulsatya** [comment]
Sama ukuran stempel dan bentuknya apakah bulat, kotak?
